group_size: -1
n_items: 8573
n_neg_test_from_sampling: 0
n_neg_train_from_sampling: 0
n_neg_valid_from_sampling: 0
n_users: 12659
test_file_format: user-item
train_file_format: user-item
user_history_file_format: user-item_seq
valid_file_format: user-item
